import { backfillRecipeShareTokens } from "./recipes";

type Queryable = {
  query: (text: string, values?: unknown[]) => Promise<{ rows: Array<Record<string, unknown>> }>;
};

type TransactionalQueryable = Queryable & {
  release?: () => void;
};

type PoolLike = Queryable & {
  connect?: () => Promise<TransactionalQueryable>;
};

type Migration = {
  id: string;
  description: string;
  statements: string[];
  run?: (client: Queryable) => Promise<void>;
};

export const MIGRATIONS: Migration[] = [
  {
    id: "001_core_schema",
    description: "Create application tables and align legacy columns",
    statements: [
      `
        CREATE TABLE IF NOT EXISTS products (
          id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          name TEXT NOT NULL,
          store TEXT,
          url TEXT,
          acquired BOOLEAN NOT NULL DEFAULT FALSE,
          is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
          acquired_at TEXT,
          deleted_at TEXT,
          created_at TEXT NOT NULL
        )
      `,
      `ALTER TABLE products ADD COLUMN IF NOT EXISTS name TEXT`,
      `ALTER TABLE products ADD COLUMN IF NOT EXISTS store TEXT`,
      `ALTER TABLE products ADD COLUMN IF NOT EXISTS url TEXT`,
      `ALTER TABLE products ADD COLUMN IF NOT EXISTS acquired BOOLEAN NOT NULL DEFAULT FALSE`,
      `ALTER TABLE products ADD COLUMN IF NOT EXISTS is_deleted BOOLEAN NOT NULL DEFAULT FALSE`,
      `ALTER TABLE products ADD COLUMN IF NOT EXISTS acquired_at TEXT`,
      `ALTER TABLE products ADD COLUMN IF NOT EXISTS deleted_at TEXT`,
      `ALTER TABLE products ADD COLUMN IF NOT EXISTS created_at TEXT`,
      `ALTER TABLE products ALTER COLUMN acquired SET DEFAULT FALSE`,
      `ALTER TABLE products ALTER COLUMN is_deleted SET DEFAULT FALSE`,

      `
        CREATE TABLE IF NOT EXISTS recipes (
          id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          title TEXT,
          course TEXT,
          url TEXT,
          ingredients TEXT,
          instructions TEXT,
          notes TEXT,
          created_at TEXT NOT NULL
        )
      `,
      `ALTER TABLE recipes ADD COLUMN IF NOT EXISTS title TEXT`,
      `ALTER TABLE recipes ADD COLUMN IF NOT EXISTS course TEXT`,
      `ALTER TABLE recipes ADD COLUMN IF NOT EXISTS url TEXT`,
      `ALTER TABLE recipes ADD COLUMN IF NOT EXISTS ingredients TEXT`,
      `ALTER TABLE recipes ADD COLUMN IF NOT EXISTS instructions TEXT`,
      `ALTER TABLE recipes ADD COLUMN IF NOT EXISTS notes TEXT`,
      `ALTER TABLE recipes ADD COLUMN IF NOT EXISTS created_at TEXT`,
      `ALTER TABLE recipes DROP COLUMN IF EXISTS description`,

      `
        CREATE TABLE IF NOT EXISTS todos (
          id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          title TEXT NOT NULL,
          due_date TEXT,
          completed BOOLEAN NOT NULL DEFAULT FALSE,
          completed_at TEXT,
          created_at TEXT NOT NULL
        )
      `,
      `ALTER TABLE todos ADD COLUMN IF NOT EXISTS title TEXT`,
      `ALTER TABLE todos ADD COLUMN IF NOT EXISTS due_date TEXT`,
      `ALTER TABLE todos ADD COLUMN IF NOT EXISTS completed BOOLEAN NOT NULL DEFAULT FALSE`,
      `ALTER TABLE todos ADD COLUMN IF NOT EXISTS completed_at TEXT`,
      `ALTER TABLE todos ADD COLUMN IF NOT EXISTS created_at TEXT`,
      `ALTER TABLE todos ALTER COLUMN completed SET DEFAULT FALSE`,

      `
        CREATE TABLE IF NOT EXISTS resource_versions (
          resource VARCHAR(64) PRIMARY KEY,
          version BIGINT NOT NULL DEFAULT 0,
          updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
        )
      `,
      `ALTER TABLE resource_versions ADD COLUMN IF NOT EXISTS version BIGINT NOT NULL DEFAULT 0`,
      `ALTER TABLE resource_versions ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()`,
    ],
  },
  {
    id: "002_recipe_share_tokens",
    description: "Add unguessable share tokens for public recipe links",
    statements: [
      `ALTER TABLE recipes ADD COLUMN IF NOT EXISTS share_token TEXT`,
    ],
    run: async (client) => {
      await backfillRecipeShareTokens(client);
      await client.query(
        `CREATE UNIQUE INDEX IF NOT EXISTS recipes_share_token_idx ON recipes (share_token)`,
      );
      await client.query(`ALTER TABLE recipes ALTER COLUMN share_token SET NOT NULL`);
    },
  },
  {
    id: "003_gift_ideas",
    description: "Create private gift ideas table",
    statements: [
      `
        CREATE TABLE IF NOT EXISTS gift_ideas (
          id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          owner_username TEXT NOT NULL,
          recipient_name TEXT NOT NULL,
          title TEXT NOT NULL,
          url TEXT,
          notes TEXT,
          purchased BOOLEAN NOT NULL DEFAULT FALSE,
          created_at TEXT NOT NULL
        )
      `,
      `ALTER TABLE gift_ideas ADD COLUMN IF NOT EXISTS owner_username TEXT`,
      `ALTER TABLE gift_ideas ADD COLUMN IF NOT EXISTS recipient_name TEXT`,
      `ALTER TABLE gift_ideas ADD COLUMN IF NOT EXISTS title TEXT`,
      `ALTER TABLE gift_ideas ADD COLUMN IF NOT EXISTS url TEXT`,
      `ALTER TABLE gift_ideas ADD COLUMN IF NOT EXISTS notes TEXT`,
      `ALTER TABLE gift_ideas ADD COLUMN IF NOT EXISTS purchased BOOLEAN NOT NULL DEFAULT FALSE`,
      `ALTER TABLE gift_ideas ADD COLUMN IF NOT EXISTS created_at TEXT`,
      `ALTER TABLE gift_ideas ALTER COLUMN purchased SET DEFAULT FALSE`,
      `
        CREATE INDEX IF NOT EXISTS gift_ideas_owner_recipient_idx
        ON gift_ideas (owner_username, recipient_name, created_at DESC)
      `,
    ],
  },
  {
    id: "004_todo_schedule_fields",
    description: "Add due time and webcal fields to todos",
    statements: [
      `ALTER TABLE todos ADD COLUMN IF NOT EXISTS due_time TEXT`,
      `ALTER TABLE todos ADD COLUMN IF NOT EXISTS webcal TEXT`,
    ],
  },
  {
    id: "005_garden_planner",
    description: "Create shared garden planner storage",
    statements: [
      `
        CREATE TABLE IF NOT EXISTS garden_plans (
          id INTEGER PRIMARY KEY,
          garden JSONB NOT NULL,
          beds JSONB NOT NULL,
          updated_at TEXT NOT NULL
        )
      `,
      `ALTER TABLE garden_plans ADD COLUMN IF NOT EXISTS garden JSONB`,
      `ALTER TABLE garden_plans ADD COLUMN IF NOT EXISTS beds JSONB`,
      `ALTER TABLE garden_plans ADD COLUMN IF NOT EXISTS updated_at TEXT`,
    ],
  },
  {
    id: "006_wishlist_product_order",
    description: "Add persistent manual ordering to wishlist products",
    statements: [
      `ALTER TABLE products ADD COLUMN IF NOT EXISTS sort_order BIGINT`,
      `
        WITH ranked AS (
          SELECT
            id,
            ROW_NUMBER() OVER (ORDER BY created_at DESC NULLS LAST, id DESC) AS position
          FROM products
          WHERE sort_order IS NULL
        )
        UPDATE products
        SET sort_order = ranked.position
        FROM ranked
        WHERE products.id = ranked.id
      `,
      `ALTER TABLE products ALTER COLUMN sort_order SET DEFAULT 0`,
      `ALTER TABLE products ALTER COLUMN sort_order SET NOT NULL`,
      `
        CREATE INDEX IF NOT EXISTS products_store_sort_order_idx
        ON products (store, sort_order, id)
      `,
    ],
  },
  {
    id: "007_meal_planner_and_lists",
    description: "Create weekly meal planner and reusable checklist storage",
    statements: [
      `
        CREATE TABLE IF NOT EXISTS meal_plan_entries (
          id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          meal_date TEXT NOT NULL,
          meal_type TEXT NOT NULL,
          recipe_id INTEGER REFERENCES recipes(id) ON DELETE SET NULL,
          title TEXT,
          created_at TEXT NOT NULL
        )
      `,
      `
        CREATE INDEX IF NOT EXISTS meal_plan_entries_date_idx
        ON meal_plan_entries (meal_date, meal_type, created_at)
      `,
      `
        CREATE TABLE IF NOT EXISTS reusable_lists (
          id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          name TEXT NOT NULL,
          is_template BOOLEAN NOT NULL DEFAULT FALSE,
          created_at TEXT NOT NULL
        )
      `,
      `
        CREATE TABLE IF NOT EXISTS reusable_list_items (
          id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          list_id INTEGER NOT NULL REFERENCES reusable_lists(id) ON DELETE CASCADE,
          title TEXT NOT NULL,
          checked BOOLEAN NOT NULL DEFAULT FALSE,
          sort_order BIGINT NOT NULL DEFAULT 0,
          created_at TEXT NOT NULL
        )
      `,
      `
        CREATE INDEX IF NOT EXISTS reusable_list_items_list_order_idx
        ON reusable_list_items (list_id, sort_order, id)
      `,
    ],
  },
  {
    id: "008_reusable_list_archiving",
    description: "Allow reusable lists to be archived as templates",
    statements: [
      `ALTER TABLE reusable_lists ADD COLUMN IF NOT EXISTS archived BOOLEAN NOT NULL DEFAULT FALSE`,
      `
        CREATE INDEX IF NOT EXISTS reusable_lists_archived_created_idx
        ON reusable_lists (archived, created_at, id)
      `,
    ],
  },
  {
    id: "009_wishlist_offline_idempotency",
    description: "Prevent duplicate wishlist items when offline changes replay",
    statements: [
      `ALTER TABLE products ADD COLUMN IF NOT EXISTS offline_client_id TEXT`,
      `
        CREATE UNIQUE INDEX IF NOT EXISTS products_offline_client_id_idx
        ON products (offline_client_id)
        WHERE offline_client_id IS NOT NULL
      `,
    ],
  },
  {
    id: "010_reusable_list_completion",
    description: "Rename reusable list archiving to completion",
    statements: [
      `ALTER TABLE reusable_lists RENAME COLUMN archived TO completed`,
      `DROP INDEX IF EXISTS reusable_lists_archived_created_idx`,
      `
        CREATE INDEX IF NOT EXISTS reusable_lists_completed_created_idx
        ON reusable_lists (completed, created_at, id)
      `,
    ],
  },
  {
    id: "011_reusable_list_templates",
    description: "Add an explicit template state for reusable lists",
    statements: [
      `ALTER TABLE reusable_lists ADD COLUMN IF NOT EXISTS is_template BOOLEAN NOT NULL DEFAULT FALSE`,
      `
        CREATE INDEX IF NOT EXISTS reusable_lists_template_created_idx
        ON reusable_lists (is_template, completed, created_at, id)
      `,
    ],
  },
  {
    id: "012_page_usage",
    description: "Store privacy-preserving daily page usage aggregates",
    statements: [
      `
        CREATE TABLE IF NOT EXISTS page_usage_daily (
          usage_date DATE NOT NULL DEFAULT CURRENT_DATE,
          page_path TEXT NOT NULL,
          visitor_hash TEXT NOT NULL,
          view_count BIGINT NOT NULL DEFAULT 1,
          first_seen_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
          last_seen_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
          PRIMARY KEY (usage_date, page_path, visitor_hash)
        )
      `,
      `
        CREATE INDEX IF NOT EXISTS page_usage_daily_path_date_idx
        ON page_usage_daily (page_path, usage_date DESC)
      `,
    ],
  },
  {
    id: "013_deployment_history",
    description: "Record successful application deployments for the private admin page",
    statements: [
      `
        CREATE TABLE IF NOT EXISTS deployment_events (
          id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          commit_sha TEXT NOT NULL,
          deployed_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
        )
      `,
      `
        CREATE INDEX IF NOT EXISTS deployment_events_deployed_at_idx
        ON deployment_events (deployed_at DESC)
      `,
    ],
  },
  {
    id: "014_feedback_backlog",
    description: "Store authenticated page feedback for the private backlog",
    statements: [
      `
        CREATE TABLE IF NOT EXISTS feedback_items (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          page_path TEXT NOT NULL,
          message TEXT NOT NULL,
          status TEXT NOT NULL DEFAULT 'open'
            CHECK (status IN ('open', 'in_progress', 'done')),
          created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
          updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
        )
      `,
      `
        CREATE INDEX IF NOT EXISTS feedback_items_status_created_idx
        ON feedback_items (status, created_at DESC)
      `,
    ],
  },
  {
    id: "015_todo_reminder_settings",
    description: "Add per-todo reminder settings",
    statements: [
      `ALTER TABLE todos ADD COLUMN IF NOT EXISTS reminder_setting TEXT`,
      `
        UPDATE todos
        SET reminder_setting = 'default'
        WHERE reminder_setting IS NULL
          OR reminder_setting NOT IN (
            'default', 'off', '15m', '30m', '1h', '2h', '1d', '1w',
            'at_due_time', 'previous_evening'
          )
      `,
      `ALTER TABLE todos ALTER COLUMN reminder_setting SET DEFAULT 'default'`,
      `ALTER TABLE todos ALTER COLUMN reminder_setting SET NOT NULL`,
    ],
  },
  {
    id: "016_harvest_count",
    description: "Store vegetable harvest counts and undoable harvest entries",
    statements: [
      `
        CREATE TABLE IF NOT EXISTS harvest_vegetables (
          id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          name TEXT NOT NULL,
          normalized_name TEXT NOT NULL UNIQUE,
          created_at TEXT NOT NULL
        )
      `,
      `
        CREATE TABLE IF NOT EXISTS harvest_entries (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          vegetable_id INTEGER NOT NULL REFERENCES harvest_vegetables(id) ON DELETE CASCADE,
          quantity INTEGER NOT NULL CHECK (quantity > 0),
          harvested_on DATE NOT NULL,
          created_at TEXT NOT NULL
        )
      `,
      `
        CREATE INDEX IF NOT EXISTS harvest_entries_date_idx
        ON harvest_entries (harvested_on DESC, created_at DESC, id DESC)
      `,
      `
        CREATE INDEX IF NOT EXISTS harvest_entries_vegetable_idx
        ON harvest_entries (vegetable_id, harvested_on DESC, created_at DESC)
      `,
    ],
  },
  {
    id: "017_harvest_units",
    description: "Support unit-aware harvest quantities including kilograms",
    statements: [
      `
        ALTER TABLE harvest_entries
        ALTER COLUMN quantity TYPE NUMERIC(10, 2)
        USING quantity::numeric
      `,
      `
        ALTER TABLE harvest_entries
        ADD COLUMN IF NOT EXISTS unit TEXT NOT NULL DEFAULT 'count'
      `,
      `
        ALTER TABLE harvest_entries
        ADD CONSTRAINT harvest_entries_unit_check
        CHECK (unit IN ('count', 'kg'))
      `,
    ],
  },
  {
    id: "018_harvest_grams",
    description: "Store harvest weights in grams instead of kilograms",
    statements: [
      `
        ALTER TABLE harvest_entries
        ALTER COLUMN quantity TYPE NUMERIC(12, 2)
        USING quantity::numeric
      `,
      `
        ALTER TABLE harvest_entries
        DROP CONSTRAINT IF EXISTS harvest_entries_unit_check
      `,
      `
        UPDATE harvest_entries
        SET quantity = quantity * 1000,
            unit = 'g'
        WHERE unit = 'kg'
      `,
      `
        ALTER TABLE harvest_entries
        ADD CONSTRAINT harvest_entries_unit_check
        CHECK (unit IN ('count', 'g'))
      `,
    ],
  },
  {
    id: "019_energy_meter",
    description: "Store energy meter readings, prices, and imported household history",
    statements: [
      `
        CREATE TABLE IF NOT EXISTS energy_meter_readings (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          reading_date DATE NOT NULL UNIQUE,
          meter_kwh NUMERIC(12, 2) NOT NULL CHECK (meter_kwh >= 0),
          created_at TEXT NOT NULL
        )
      `,
      `
        CREATE INDEX IF NOT EXISTS energy_meter_readings_date_idx
        ON energy_meter_readings (reading_date DESC, id DESC)
      `,
      `
        CREATE TABLE IF NOT EXISTS energy_price_settings (
          id INTEGER PRIMARY KEY CHECK (id = 1),
          fixed_monthly_cost NUMERIC(10, 4) NOT NULL CHECK (fixed_monthly_cost >= 0),
          variable_cost_per_kwh NUMERIC(10, 4) NOT NULL CHECK (variable_cost_per_kwh >= 0),
          currency TEXT NOT NULL DEFAULT 'EUR',
          updated_at TEXT NOT NULL
        )
      `,
      `
        INSERT INTO energy_price_settings
          (id, fixed_monthly_cost, variable_cost_per_kwh, currency, updated_at)
        VALUES (1, 10.90, 0.3490, 'EUR', '2026-08-05T00:00:00.000Z')
        ON CONFLICT (id) DO NOTHING
      `,
      `
        INSERT INTO energy_meter_readings (reading_date, meter_kwh, created_at)
        VALUES
          ('2025-09-21', 108996, '2025-09-21T00:00:00.000Z'),
          ('2025-10-03', 109117, '2025-10-03T00:00:00.000Z'),
          ('2025-10-11', 109210, '2025-10-11T00:00:00.000Z'),
          ('2025-10-17', 109249, '2025-10-17T00:00:00.000Z'),
          ('2025-10-24', 109301, '2025-10-24T00:00:00.000Z'),
          ('2025-11-14', 109451, '2025-11-14T00:00:00.000Z'),
          ('2025-12-05', 109621, '2025-12-05T00:00:00.000Z'),
          ('2025-12-30', 109767, '2025-12-30T00:00:00.000Z'),
          ('2026-01-26', 109896, '2026-01-26T00:00:00.000Z'),
          ('2026-01-31', 109930, '2026-01-31T00:00:00.000Z'),
          ('2026-02-15', 110037, '2026-02-15T00:00:00.000Z'),
          ('2026-03-11', 110181, '2026-03-11T00:00:00.000Z'),
          ('2026-04-12', 110387, '2026-04-12T00:00:00.000Z'),
          ('2026-05-10', 110579, '2026-05-10T00:00:00.000Z'),
          ('2026-05-18', 110640, '2026-05-18T00:00:00.000Z'),
          ('2026-05-23', 110674, '2026-05-23T00:00:00.000Z'),
          ('2026-06-23', 110829, '2026-06-23T00:00:00.000Z'),
          ('2026-06-28', 110895, '2026-06-28T00:00:00.000Z'),
          ('2026-07-09', 110944, '2026-07-09T00:00:00.000Z'),
          ('2026-07-27', 111063, '2026-07-27T00:00:00.000Z'),
          ('2026-08-05', 111111, '2026-08-05T00:00:00.000Z')
        ON CONFLICT (reading_date) DO NOTHING
      `,
    ],
  },
  {
    id: "020_harvest_crop_units",
    description: "Give each harvest crop one fixed unit",
    statements: [
      `
        ALTER TABLE harvest_vegetables
        ADD COLUMN IF NOT EXISTS unit TEXT NOT NULL DEFAULT 'count'
      `,
      `
        UPDATE harvest_vegetables AS vegetables
        SET unit = latest.unit
        FROM (
          SELECT DISTINCT ON (vegetable_id)
            vegetable_id,
            unit
          FROM harvest_entries
          ORDER BY vegetable_id, created_at DESC, id DESC
        ) AS latest
        WHERE vegetables.id = latest.vegetable_id
      `,
      `
        ALTER TABLE harvest_vegetables
        ADD CONSTRAINT harvest_vegetables_unit_check
        CHECK (unit IN ('count', 'g'))
      `,
    ],
  },
  {
    id: "021_coffee_tracker",
    description: "Store coffee purchases, ratings, and preferences",
    statements: [
      `
        CREATE TABLE IF NOT EXISTS coffee_entries (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          name TEXT NOT NULL,
          brand TEXT,
          kind TEXT NOT NULL,
          rating SMALLINT NOT NULL CHECK (rating BETWEEN 1 AND 5),
          verdict TEXT NOT NULL CHECK (verdict IN ('liked', 'okay', 'disliked')),
          purchased_on DATE NOT NULL,
          notes TEXT,
          created_at TEXT NOT NULL,
          updated_at TEXT NOT NULL
        )
      `,
      `ALTER TABLE coffee_entries ADD COLUMN IF NOT EXISTS name TEXT`,
      `ALTER TABLE coffee_entries ADD COLUMN IF NOT EXISTS brand TEXT`,
      `ALTER TABLE coffee_entries ADD COLUMN IF NOT EXISTS kind TEXT`,
      `ALTER TABLE coffee_entries ADD COLUMN IF NOT EXISTS rating SMALLINT`,
      `ALTER TABLE coffee_entries ADD COLUMN IF NOT EXISTS verdict TEXT`,
      `ALTER TABLE coffee_entries ADD COLUMN IF NOT EXISTS purchased_on DATE`,
      `ALTER TABLE coffee_entries ADD COLUMN IF NOT EXISTS notes TEXT`,
      `ALTER TABLE coffee_entries ADD COLUMN IF NOT EXISTS created_at TEXT`,
      `ALTER TABLE coffee_entries ADD COLUMN IF NOT EXISTS updated_at TEXT`,
      `
        CREATE INDEX IF NOT EXISTS coffee_entries_purchased_on_idx
        ON coffee_entries (purchased_on DESC, id DESC)
      `,
    ],
  },
  {
    id: "022_simplify_coffee_tracker",
    description: "Simplify coffee entries and move ratings to a ten point scale",
    statements: [
      `ALTER TABLE coffee_entries ALTER COLUMN kind DROP NOT NULL`,
      `ALTER TABLE coffee_entries ALTER COLUMN verdict DROP NOT NULL`,
      `ALTER TABLE coffee_entries DROP CONSTRAINT IF EXISTS coffee_entries_rating_check`,
      `
        ALTER TABLE coffee_entries
        ALTER COLUMN rating TYPE NUMERIC(3, 1)
        USING ROUND(rating::numeric * 2, 1)
      `,
      `
        ALTER TABLE coffee_entries
        ADD CONSTRAINT coffee_entries_rating_check
        CHECK (rating BETWEEN 0 AND 10 AND rating = ROUND(rating, 1))
      `,
    ],
  },
];

async function withClient<T>(
  pool: PoolLike,
  callback: (client: TransactionalQueryable) => Promise<T>,
) {
  if (!pool.connect) {
    return callback(pool);
  }

  const client = await pool.connect();
  try {
    return await callback(client);
  } finally {
    client.release?.();
  }
}

async function ensureMigrationTable(client: Queryable) {
  await client.query(`
    CREATE TABLE IF NOT EXISTS schema_migrations (
      id TEXT PRIMARY KEY,
      description TEXT NOT NULL,
      applied_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    )
  `);
}

export async function getAppliedMigrationIds(client: Queryable) {
  await ensureMigrationTable(client);
  const result = await client.query(
    `SELECT id FROM schema_migrations ORDER BY applied_at ASC, id ASC`,
  );
  return new Set(result.rows.map((row) => String(row.id)));
}

export async function runMigrations(pool: PoolLike) {
  return withClient(pool, async (client) => {
    const appliedIds = await getAppliedMigrationIds(client);
    const executed: string[] = [];

    for (const migration of MIGRATIONS) {
      if (appliedIds.has(migration.id)) {
        continue;
      }

      await client.query("BEGIN");

      try {
        for (const statement of migration.statements) {
          await client.query(statement);
        }

        if (migration.run) {
          await migration.run(client);
        }

        await client.query(
          `
            INSERT INTO schema_migrations (id, description)
            VALUES ($1, $2)
          `,
          [migration.id, migration.description],
        );
        await client.query("COMMIT");
        executed.push(migration.id);
      } catch (error) {
        await client.query("ROLLBACK");
        throw error;
      }
    }

    return executed;
  });
}
