import { backfillRecipeShareTokens } from "@/lib/server/recipes";

type Queryable = {
  query: (text: string, values?: unknown[]) => Promise<{ rows: Array<Record<string, unknown>> }>;
};

type TransactionalQueryable = Queryable & {
  release?: () => void;
};

type PoolLike = Queryable & {
  connect?: () => Promise<TransactionalQueryable>;
};

type Migration = {
  id: string;
  description: string;
  statements: string[];
  run?: (client: Queryable) => Promise<void>;
};

export const MIGRATIONS: Migration[] = [
  {
    id: "001_core_schema",
    description: "Create application tables and align legacy columns",
    statements: [
      `
        CREATE TABLE IF NOT EXISTS products (
          id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          name TEXT NOT NULL,
          store TEXT,
          url TEXT,
          acquired BOOLEAN NOT NULL DEFAULT FALSE,
          is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
          acquired_at TEXT,
          deleted_at TEXT,
          created_at TEXT NOT NULL
        )
      `,
      `ALTER TABLE products ADD COLUMN IF NOT EXISTS name TEXT`,
      `ALTER TABLE products ADD COLUMN IF NOT EXISTS store TEXT`,
      `ALTER TABLE products ADD COLUMN IF NOT EXISTS url TEXT`,
      `ALTER TABLE products ADD COLUMN IF NOT EXISTS acquired BOOLEAN NOT NULL DEFAULT FALSE`,
      `ALTER TABLE products ADD COLUMN IF NOT EXISTS is_deleted BOOLEAN NOT NULL DEFAULT FALSE`,
      `ALTER TABLE products ADD COLUMN IF NOT EXISTS acquired_at TEXT`,
      `ALTER TABLE products ADD COLUMN IF NOT EXISTS deleted_at TEXT`,
      `ALTER TABLE products ADD COLUMN IF NOT EXISTS created_at TEXT`,
      `ALTER TABLE products ALTER COLUMN acquired SET DEFAULT FALSE`,
      `ALTER TABLE products ALTER COLUMN is_deleted SET DEFAULT FALSE`,

      `
        CREATE TABLE IF NOT EXISTS recipes (
          id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          title TEXT,
          course TEXT,
          url TEXT,
          ingredients TEXT,
          instructions TEXT,
          notes TEXT,
          created_at TEXT NOT NULL
        )
      `,
      `ALTER TABLE recipes ADD COLUMN IF NOT EXISTS title TEXT`,
      `ALTER TABLE recipes ADD COLUMN IF NOT EXISTS course TEXT`,
      `ALTER TABLE recipes ADD COLUMN IF NOT EXISTS url TEXT`,
      `ALTER TABLE recipes ADD COLUMN IF NOT EXISTS ingredients TEXT`,
      `ALTER TABLE recipes ADD COLUMN IF NOT EXISTS instructions TEXT`,
      `ALTER TABLE recipes ADD COLUMN IF NOT EXISTS notes TEXT`,
      `ALTER TABLE recipes ADD COLUMN IF NOT EXISTS created_at TEXT`,
      `ALTER TABLE recipes DROP COLUMN IF EXISTS description`,

      `
        CREATE TABLE IF NOT EXISTS todos (
          id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          title TEXT NOT NULL,
          due_date TEXT,
          completed BOOLEAN NOT NULL DEFAULT FALSE,
          completed_at TEXT,
          created_at TEXT NOT NULL
        )
      `,
      `ALTER TABLE todos ADD COLUMN IF NOT EXISTS title TEXT`,
      `ALTER TABLE todos ADD COLUMN IF NOT EXISTS due_date TEXT`,
      `ALTER TABLE todos ADD COLUMN IF NOT EXISTS completed BOOLEAN NOT NULL DEFAULT FALSE`,
      `ALTER TABLE todos ADD COLUMN IF NOT EXISTS completed_at TEXT`,
      `ALTER TABLE todos ADD COLUMN IF NOT EXISTS created_at TEXT`,
      `ALTER TABLE todos ALTER COLUMN completed SET DEFAULT FALSE`,

      `
        CREATE TABLE IF NOT EXISTS resource_versions (
          resource VARCHAR(64) PRIMARY KEY,
          version BIGINT NOT NULL DEFAULT 0,
          updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
        )
      `,
      `ALTER TABLE resource_versions ADD COLUMN IF NOT EXISTS version BIGINT NOT NULL DEFAULT 0`,
      `ALTER TABLE resource_versions ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()`,
    ],
  },
  {
    id: "002_recipe_share_tokens",
    description: "Add unguessable share tokens for public recipe links",
    statements: [
      `ALTER TABLE recipes ADD COLUMN IF NOT EXISTS share_token TEXT`,
    ],
    run: async (client) => {
      await backfillRecipeShareTokens(client);
      await client.query(
        `CREATE UNIQUE INDEX IF NOT EXISTS recipes_share_token_idx ON recipes (share_token)`,
      );
      await client.query(`ALTER TABLE recipes ALTER COLUMN share_token SET NOT NULL`);
    },
  },
  {
    id: "003_gift_ideas",
    description: "Create private gift ideas table",
    statements: [
      `
        CREATE TABLE IF NOT EXISTS gift_ideas (
          id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          owner_username TEXT NOT NULL,
          recipient_name TEXT NOT NULL,
          title TEXT NOT NULL,
          url TEXT,
          notes TEXT,
          purchased BOOLEAN NOT NULL DEFAULT FALSE,
          created_at TEXT NOT NULL
        )
      `,
      `ALTER TABLE gift_ideas ADD COLUMN IF NOT EXISTS owner_username TEXT`,
      `ALTER TABLE gift_ideas ADD COLUMN IF NOT EXISTS recipient_name TEXT`,
      `ALTER TABLE gift_ideas ADD COLUMN IF NOT EXISTS title TEXT`,
      `ALTER TABLE gift_ideas ADD COLUMN IF NOT EXISTS url TEXT`,
      `ALTER TABLE gift_ideas ADD COLUMN IF NOT EXISTS notes TEXT`,
      `ALTER TABLE gift_ideas ADD COLUMN IF NOT EXISTS purchased BOOLEAN NOT NULL DEFAULT FALSE`,
      `ALTER TABLE gift_ideas ADD COLUMN IF NOT EXISTS created_at TEXT`,
      `ALTER TABLE gift_ideas ALTER COLUMN purchased SET DEFAULT FALSE`,
      `
        CREATE INDEX IF NOT EXISTS gift_ideas_owner_recipient_idx
        ON gift_ideas (owner_username, recipient_name, created_at DESC)
      `,
    ],
  },
];

async function withClient<T>(
  pool: PoolLike,
  callback: (client: TransactionalQueryable) => Promise<T>,
) {
  if (!pool.connect) {
    return callback(pool);
  }

  const client = await pool.connect();
  try {
    return await callback(client);
  } finally {
    client.release?.();
  }
}

async function ensureMigrationTable(client: Queryable) {
  await client.query(`
    CREATE TABLE IF NOT EXISTS schema_migrations (
      id TEXT PRIMARY KEY,
      description TEXT NOT NULL,
      applied_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    )
  `);
}

export async function getAppliedMigrationIds(client: Queryable) {
  await ensureMigrationTable(client);
  const result = await client.query(
    `SELECT id FROM schema_migrations ORDER BY applied_at ASC, id ASC`,
  );
  return new Set(result.rows.map((row) => String(row.id)));
}

export async function runMigrations(pool: PoolLike) {
  return withClient(pool, async (client) => {
    const appliedIds = await getAppliedMigrationIds(client);
    const executed: string[] = [];

    for (const migration of MIGRATIONS) {
      if (appliedIds.has(migration.id)) {
        continue;
      }

      await client.query("BEGIN");

      try {
        for (const statement of migration.statements) {
          await client.query(statement);
        }

        if (migration.run) {
          await migration.run(client);
        }

        await client.query(
          `
            INSERT INTO schema_migrations (id, description)
            VALUES ($1, $2)
          `,
          [migration.id, migration.description],
        );
        await client.query("COMMIT");
        executed.push(migration.id);
      } catch (error) {
        await client.query("ROLLBACK");
        throw error;
      }
    }

    return executed;
  });
}
